// Builds the self-contained web simulation into sim/web/dist:
//   dist/index.html      page with gait.js + app.js inlined as one module
//   dist/geometry.json   robot geometry (generated by cad/params.py)
//   dist/meshes.json     visual meshes (cad/hexabot_cad.py), base64 STL
//
//   node sim/web/build.mjs && python3 -m http.server -d sim/web/dist 8000
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const repo = path.resolve(here, '../..');
const out = path.join(here, 'dist');
fs.mkdirSync(out, { recursive: true });

const gait = fs.readFileSync(path.join(here, 'src/gait.js'), 'utf8').replace(/^export /gm, '');
let app = fs.readFileSync(path.join(here, 'src/app.js'), 'utf8');
app = app.replace(/^import \{[^}]*\} from '\.\/gait\.js';\n/m, '');
const imports = app.match(/^import .*;$/gm) || [];
app = app.replace(/^import .*;\n/gm, '');
const bundle = [...imports, '', '// ---- gait.js ----', gait, '// ---- app.js ----', app].join('\n');

const tag = '<script type="module" src="src/app.js"></script>';
const html = fs.readFileSync(path.join(here, 'index.html'), 'utf8');
if (!html.includes(tag)) throw new Error('index.html: app script tag not found');
fs.writeFileSync(path.join(out, 'index.html'), html.replace(tag, () => `<script type="module">\n${bundle}\n</script>`));

fs.copyFileSync(path.join(here, 'assets/geometry.json'), path.join(out, 'geometry.json'));
// Meshes travel as one JSON file of base64 STL blobs (artifact hosting
// serves .json but not .stl).
const meshDir = path.join(repo, 'src/hexabot_description/meshes/visual');
const pack = {};
for (const f of fs.readdirSync(meshDir).sort()) {
  if (!f.endsWith('.stl')) continue;
  pack[f.replace(/\.stl$/, '')] = fs.readFileSync(path.join(meshDir, f)).toString('base64');
}
fs.rmSync(path.join(out, 'meshes'), { recursive: true, force: true });
fs.writeFileSync(path.join(out, 'meshes.json'), JSON.stringify(pack));
const kb = (f) => (fs.statSync(path.join(out, f)).size / 1024).toFixed(0);
console.log(`dist/index.html (${kb('index.html')} kB), meshes.json (${kb('meshes.json')} kB, ${Object.keys(pack).length} meshes)`);
