// GENERATED by cad/params.py - do not edit by hand.
#pragma once

#include <array>

namespace hexabot_locomotion::defaults
{
constexpr std::array<double, 6> kMountX{0.12, 0.0, -0.12, 0.12, 0.0, -0.12};
constexpr std::array<double, 6> kMountY{0.065, 0.095, 0.065, -0.065, -0.095, -0.065};
constexpr std::array<double, 6> kMountYaw{0.785398, 1.570796, 2.356194, -0.785398, -1.570796, -2.356194};
constexpr double kCoxaLength = 0.042;
constexpr double kFemurLength = 0.088;
constexpr double kTibiaLength = 0.135;
constexpr std::array<double, 2> kCoxaLimits{-0.698132, 0.698132};
constexpr std::array<double, 2> kFemurLimits{-0.785398, 1.658063};
constexpr std::array<double, 2> kTibiaLimits{-1.134464, 1.308997};
constexpr double kStanceRadius = 0.127;
constexpr double kBodyHeight = 0.1;
constexpr std::array<double, 2> kBodyHeightRange{0.055, 0.15};
constexpr double kStepHeight = 0.045;
constexpr double kStepHeightMax = 0.08;
}  // namespace hexabot_locomotion::defaults
